volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oayyoub/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oayyoub/data/mariadb

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    secrets:
      - credentials
      - db_password
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - frontend-network
    restart: unless-stopped

